# Generated by Django 2.1.5 on 2019-01-21 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('phone_number', models.CharField(max_length=232, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=232)),
                ('category', models.CharField(max_length=232)),
                ('picture', models.ImageField(upload_to='uploads/')),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DishCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date_time', models.DateTimeField()),
                ('comment', models.TextField(max_length=232, null=True)),
                ('person_count', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[('NEW', 1), ('IN PROGRESS', 2), ('READY TO MEAL', 3), ('FINISHED', 4)], default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Customer')),
                ('dishes', models.ManyToManyField(through='main.DishCount', to='main.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('name', models.CharField(max_length=232)),
                ('description', models.TextField(max_length=232)),
                ('picture', models.ImageField(upload_to='uploads/')),
                ('phone_number', models.CharField(max_length=232, primary_key=True, serialize=False)),
                ('coord_x', models.DecimalField(decimal_places=10, max_digits=40)),
                ('coord_y', models.DecimalField(decimal_places=10, max_digits=40)),
                ('dishes', models.ManyToManyField(to='main.Dish')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Restaurant'),
        ),
        migrations.AddField(
            model_name='dishcount',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Order'),
        ),
    ]
